"use strict";
exports.__esModule = true;
var M = require("./src/math.bs");
exports.areaCircle = M.areaCircle;
exports.areaParallelogram = M.areaParallelogram;
exports.areaRectangle = M.areaRectangle;
exports.areaSquare = M.areaSquare;
exports.areaTrapezoid = M.areaTrapezoid;
exports.areaTriangle = M.areaTriangle;
exports.removeNegatives = M.removeNegatives;
exports.removePositives = M.removePositives;
exports.surfaceAreaSphere = M.surfaceAreaSphere;
