// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE
'use strict';


var pi = 4.0 * Math.atan(1.0);

function areaCircle(radius) {
  var safeRadius = radius < 0.0 ? 0.0 : radius;
  return pi * safeRadius * safeRadius;
}

function areaParallelogram(base, height) {
  var safeBase = base < 0.0 ? 0.0 : base;
  var safeHeight = height < 0.0 ? 0.0 : height;
  return safeBase * safeHeight;
}

function areaRectangle(length, width) {
  var safeLength = length < 0.0 ? 0.0 : length;
  var safeWidth = width < 0.0 ? 0.0 : width;
  return safeLength * safeWidth;
}

function areaSquare(side) {
  var safeSide = side < 0.0 ? 0.0 : side;
  return safeSide * safeSide;
}

function areaTrapezoid(base1, base2, height) {
  var safeBase1 = base1 < 0.0 ? 0.0 : base1;
  var safeBase2 = base2 < 0.0 ? 0.0 : base2;
  var safeHeight = height < 0.0 ? 0.0 : height;
  var match = safeBase1 * safeBase2 * safeHeight;
  if (match !== 0.0) {
    return 0.5 * (safeBase1 + safeBase2) * safeHeight;
  } else {
    return 0.0;
  }
}

function areaTriangle(base, height) {
  var safeBase = base < 0.0 ? 0.0 : base;
  var safeHeight = height < 0.0 ? 0.0 : height;
  return 0.5 * safeBase * safeHeight;
}

function removeNegatives(values) {
  return values.filter((function (x) {
                return x > 0.0;
              }));
}

function removePositives(values) {
  return values.filter((function (x) {
                return x < 0.0;
              }));
}

function surfaceAreaSphere(radius) {
  var safeRadius = radius < 0.0 ? 0.0 : radius;
  return 4.0 * pi * safeRadius * safeRadius;
}

exports.pi = pi;
exports.areaCircle = areaCircle;
exports.areaParallelogram = areaParallelogram;
exports.areaRectangle = areaRectangle;
exports.areaSquare = areaSquare;
exports.areaTrapezoid = areaTrapezoid;
exports.areaTriangle = areaTriangle;
exports.removeNegatives = removeNegatives;
exports.removePositives = removePositives;
exports.surfaceAreaSphere = surfaceAreaSphere;
/* pi Not a pure module */
